# Generated by Django 3.2.5 on 2021-08-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210813_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profile'},
        ),
    ]
