# Generated by Django 3.2.5 on 2021-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('in_percent', models.BooleanField(default=False, verbose_name='in percent')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
            },
        ),
    ]
