# Generated by Django 3.2.5 on 2021-08-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_couponmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
