# Generated by Django 3.2.5 on 2021-07-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttagmodel',
            options={'verbose_name': 'post tag', 'verbose_name_plural': 'post tags'},
        ),
    ]
