# Generated by Django 3.2.5 on 2021-08-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_addtocartmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtocartmodel',
            options={'verbose_name': 'add to cart', 'verbose_name_plural': 'add to cart'},
        ),
    ]
