# Generated by Django 3.2.5 on 2021-08-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_addtocartmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCartModel',
        ),
    ]
