# Generated by Django 3.2.5 on 2021-08-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_addtocartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCartModel',
        ),
    ]
