# Generated by Django 3.2.5 on 2021-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_addtocartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_en',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_uz',
            field=models.TextField(null=True, verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
    ]
